/* PLQNX 8 · ECLIPSE adaptive command interface */
(()=>{"use strict";
const body=document.body;if(!body.classList.contains("eclipse"))return;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const reduced=matchMedia("(prefers-reduced-motion:reduce)").matches;
const state={x:.5,y:.5,typing:0,lastKey:0,context:"focus",audio:false,history:[],remember:false};
try{state.remember=localStorage.getItem("plqnx_remember_intents")==="1";if(state.remember)state.history=JSON.parse(localStorage.getItem("plqnx_intent_history")||"[]").filter(item=>item&&typeof item.text==="string"&&Number.isFinite(item.at)).slice(-12)}catch{}
const hour=new Date().getHours(),daypart=hour<12?"morning":hour<17?"afternoon":"night";
const copy={morning:{title:"Good morning. What are we solving?",lead:"Start with intent. PLQNX shapes the interface around what you want to do."},afternoon:{title:"Turn intent into momentum.",lead:"One command can open the right workspace, prompt, or next step without hunting through menus."},night:{title:"Quiet interface. Big ideas.",lead:"A low-distraction canvas for building, learning and creating when the rest of the screen can disappear."}};
const title=$("#adaptiveTitle"),lead=$("#adaptiveLead");if(title)title.textContent=copy[daypart].title;if(lead)lead.textContent=copy[daypart].lead;
const mode=$("#commandMode"),speed=$("#commandSpeed"),input=$("#commandInput");
function classify(text){const t=text.toLowerCase();if(/code|build|debug|app|website|api|python|javascript|model/.test(t))return"build";if(/write|story|image|creative|design|script|logo|video|idea/.test(t))return"create";if(/data|analy|report|compare|research|metric|trend/.test(t))return"analyze";if(/learn|explain|teach|study|understand/.test(t))return"learn";return hour>=21||hour<7?"focus":"explore"}
function setContext(c){state.context=c;body.dataset.eContext=c;if(mode)mode.textContent=(c+" mode").toUpperCase();renderPredictive()}
function renderPredictive(){const host=$("#predictiveTools");if(!host)return;const c=state.context;const sets={build:[["⌘","Continue in CORE","Open a coding-ready conversation with your intent."],["▣","Break into steps","Turn a build request into a practical implementation plan."],["↗","Debug path","Focus the next prompt on errors, causes and fixes."]],create:[["✦","Creative canvas","Open CORE with a cleaner creative starting point."],["◈","Generate directions","Ask for several distinct creative directions first."],["◇","Refine one idea","Move from brainstorm to one polished concept."]],analyze:[["▤","Analysis brief","Structure a question around evidence, assumptions and output."],["◎","Compare options","Open a decision-oriented comparison prompt."],["↗","Research frame","Create a crisp research question before exploring."]],learn:[["◎","Teach me","Open a step-by-step explanation flow."],["▤","Study map","Break a topic into a compact learning sequence."],["✦","Quiz me","Turn the topic into active recall questions."]],focus:[["✦","Minimal focus","Strip the task to the single next action."],["⌘","Resume last intent","Pick up from your most recent local command."],["◎","Clarify the goal","Convert a fuzzy idea into a precise prompt."]],explore:[["✦","Explore an idea","Turn an early thought into useful directions."],["⌘","Build something","Open a practical project prompt."],["◎","Learn something","Start a clear teaching conversation."]]};host.replaceChildren();(sets[c]||sets.explore).forEach(([icon,h,p],i)=>{const card=document.createElement("article");card.className="predict-card";card.innerHTML='<div class="tag">SURFACED FOR '+c.toUpperCase()+'</div><h3>'+icon+' '+h+'</h3><p>'+p+'</p>';const b=document.createElement("button");b.type="button";b.setAttribute("aria-label",h);b.addEventListener("click",()=>{if(!input)return;const starters=["Help me "+h.toLowerCase()+": ","Turn this into a practical plan: ","Help me explore this clearly: "];input.value=starters[i%starters.length];input.focus();input.dispatchEvent(new Event("input"))});card.append(b);host.append(card)})}
function saveIntent(text,c){if(!state.remember)return;state.history.push({text:text.slice(0,180),context:c,at:Date.now()});state.history=state.history.slice(-12);try{localStorage.setItem("plqnx_intent_history",JSON.stringify(state.history));localStorage.setItem("plqnx_last_seen",String(Date.now()))}catch{}renderReturn()}
function renderReturn(){const host=$("#returnItems"),label=$("#returnLabel");if(!host)return;host.replaceChildren();const items=state.history.slice(-3).reverse();if(!items.length){if(label)label.textContent=state.remember?"NO SAVED INTENTS YET":"LOCAL MEMORY DISABLED";host.innerHTML='<div class="return-item"><i>✧</i><div><strong>No local activity yet</strong><span>Your recent command intents will appear here on this device.</span></div></div>';return}items.forEach(it=>{const d=document.createElement("div");d.className="return-item";const ago=Math.max(1,Math.round((Date.now()-it.at)/60000));d.innerHTML='<i>↗</i><div><strong></strong><span></span></div>';d.querySelector("strong").textContent=it.text;d.querySelector("span").textContent=it.context.toUpperCase()+" · "+(ago<60?ago+"m":Math.round(ago/60)+"h")+" ago · stored locally";host.append(d)});if(label)label.textContent="RECENT INTENT · THIS DEVICE"}
const historyBtn=$("#historyOpt"),memoryNotice=$("#localMemoryNotice");function memoryControls(){if(historyBtn){historyBtn.textContent=state.remember?"Local memory on":"Local memory off";historyBtn.setAttribute("aria-pressed",String(state.remember))}if(memoryNotice)memoryNotice.textContent=state.remember?"Commands are saved only in this browser. Turn this off to erase locally stored intents.":"Local command history is off. Enable it to surface recent intents on this device."}historyBtn?.addEventListener("click",()=>{state.remember=!state.remember;try{localStorage.setItem("plqnx_remember_intents",state.remember?"1":"0");if(!state.remember){localStorage.removeItem("plqnx_intent_history");localStorage.removeItem("plqnx_last_seen");state.history=[]}}catch{}memoryControls();renderReturn();toast(state.remember?"Local memory enabled on this browser.":"Local history erased and memory disabled.")});memoryControls();
if(input){input.addEventListener("input",e=>{const now=performance.now();if(state.lastKey)state.typing=.8*state.typing+.2*(1000/Math.max(60,now-state.lastKey));state.lastKey=now;if(speed)speed.textContent=state.typing?Math.round(state.typing)+" keys/min signal":"adaptive signal";setContext(classify(e.target.value));e.target.style.height="auto";e.target.style.height=Math.min(220,e.target.scrollHeight)+"px"});input.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();$("#commandForm")?.requestSubmit()}})}
$("#commandForm")?.addEventListener("submit",e=>{e.preventDefault();const text=input?.value.trim();if(!text)return;const c=classify(text);saveIntent(text,c);chime("send");location.href="./core.html?prompt="+encodeURIComponent(text)+"&mode="+encodeURIComponent(c)});
$$("[data-command]").forEach(b=>b.addEventListener("click",()=>{if(!input)return;input.value=b.dataset.command||"";input.focus();input.dispatchEvent(new Event("input"))}));
function toast(msg){const t=$("#eclipseToast");if(!t)return;t.textContent=msg;t.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove("show"),2600)}
$("#soundToggle")?.addEventListener("click",()=>{state.audio=!state.audio;try{localStorage.setItem("plqnx_sound",state.audio?"1":"0")}catch{}$("#soundToggle").textContent=state.audio?"Sound on":"Sound off";if(state.audio)chime("ready");toast(state.audio?"Subtle interface sound enabled.":"Interface sound disabled.")});try{state.audio=localStorage.getItem("plqnx_sound")==="1"}catch{}if($("#soundToggle"))$("#soundToggle").textContent=state.audio?"Sound on":"Sound off";
function chime(kind){if(!state.audio)return;try{const AC=window.AudioContext||window.webkitAudioContext,ctx=new AC(),gain=ctx.createGain(),osc=ctx.createOscillator();osc.type="sine";osc.frequency.setValueAtTime(kind==="send"?180:260,ctx.currentTime);osc.frequency.exponentialRampToValueAtTime(kind==="send"?310:420,ctx.currentTime+.17);gain.gain.setValueAtTime(.0001,ctx.currentTime);gain.gain.exponentialRampToValueAtTime(.035,ctx.currentTime+.02);gain.gain.exponentialRampToValueAtTime(.0001,ctx.currentTime+.32);osc.connect(gain);gain.connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+.34);setTimeout(()=>ctx.close(),500)}catch{}}
const Speech=window.SpeechRecognition||window.webkitSpeechRecognition;if(Speech&&$("#commandMic")){const rec=new Speech();rec.lang=$("#commandLanguage")?.value||"en-IN";rec.interimResults=true;$("#commandLanguage")?.addEventListener("change",e=>{rec.lang=e.target.value});let active=false;$("#commandMic").addEventListener("click",()=>{if(active){rec.stop();return}try{rec.start()}catch{}});rec.onstart=()=>{active=true;$("#commandMic").classList.add("listening");toast("Listening… speak your intent.")};rec.onend=()=>{active=false;$("#commandMic").classList.remove("listening")};rec.onresult=e=>{let text="";for(let i=e.resultIndex;i<e.results.length;i++)text+=e.results[i][0].transcript;if(input){input.value=text;input.dispatchEvent(new Event("input"))}}}else if($("#commandMic")){$("#commandMic").addEventListener("click",()=>toast("Speech recognition is not available in this browser."))}
renderPredictive();renderReturn();setContext(hour>=22||hour<7?"focus":"explore");document.addEventListener("pointermove",e=>{state.x=e.clientX/innerWidth;state.y=e.clientY/innerHeight},{passive:true});
if(!reduced){const canvas=$("#eclipseField"),gl=canvas?.getContext("webgl",{alpha:false,antialias:false});if(gl){const vs='attribute vec2 p;void main(){gl_Position=vec4(p,0.,1.);}';const fs='precision mediump float;uniform vec2 r;uniform vec2 m;uniform float t;uniform float k;float g(vec2 p,vec2 c,float s){return s/(.03+dot(p-c,p-c));}void main(){vec2 uv=(gl_FragCoord.xy-.5*r)/min(r.x,r.y);vec2 mm=(m-.5)*vec2(r.x/r.y,1.);float a=.015*g(uv,mm*.65,.12);float b=.012*g(uv,vec2(sin(t*.12)*.55,cos(t*.09)*.36),.10);float c=.008*g(uv,vec2(-.7,.5),.12);vec3 col=vec3(.006,.006,.016)+a*mix(vec3(.45,.25,.9),vec3(.1,.8,.95),k)+b*vec3(.42,.15,.8)+c*vec3(.2,.8,.7);gl_FragColor=vec4(col,1.);}';const compile=(type,src)=>{const sh=gl.createShader(type);gl.shaderSource(sh,src);gl.compileShader(sh);return sh},prog=gl.createProgram();gl.attachShader(prog,compile(gl.VERTEX_SHADER,vs));gl.attachShader(prog,compile(gl.FRAGMENT_SHADER,fs));gl.linkProgram(prog);gl.useProgram(prog);const buf=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buf);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,3,-1,-1,3]),gl.STATIC_DRAW);const pos=gl.getAttribLocation(prog,"p");gl.enableVertexAttribArray(pos);gl.vertexAttribPointer(pos,2,gl.FLOAT,false,0,0);const ur=gl.getUniformLocation(prog,"r"),um=gl.getUniformLocation(prog,"m"),ut=gl.getUniformLocation(prog,"t"),uk=gl.getUniformLocation(prog,"k");function size(){canvas.width=Math.max(1,innerWidth*devicePixelRatio*.72);canvas.height=Math.max(1,innerHeight*devicePixelRatio*.72);gl.viewport(0,0,canvas.width,canvas.height)}size();addEventListener("resize",size,{passive:true});const start=performance.now();(function draw(now){gl.uniform2f(ur,canvas.width,canvas.height);gl.uniform2f(um,state.x,state.y);gl.uniform1f(ut,(now-start)/1000);gl.uniform1f(uk,Math.min(1,state.typing/8));gl.drawArrays(gl.TRIANGLES,0,3);requestAnimationFrame(draw)})(start)}}
})();